server:
  port: 8000

spring:
  primary:
    datasource:
      url: jdbc:h2:~/forexdb;AUTO_SERVER=TRUE;Mode=Oracle
      platform: h2
      continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
