GET http://localhost:8000/exchange/list

###

GET http://localhost:8000/session/set
Cookie: {{session-cookie}}

> {%
client.global.set("session-cookie", response.headers.valueOf("Set-Cookie"));
%}

###

GET http://localhost:8001/session/get
Cookie: {{session-cookie}}

###

GET http://localhost:8000/exchange/from/USD/to/INR

###

GET http://localhost:8100/convert-currency/from/USD/to/INR/amount/1

###

GET http://localhost:8500/conversion/convert-currency/from/USD/to/INR/amount/1

###
