server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: http://ga-subsvn01:7990/scm/poc/spring-boot-microservices-configuration.git
          username: Jenkins
          password: pippo2017!
