server:
  port: 8500

zuul:
  routes:
    conversion-service:
      path: /**
      serviceId: conversion-service

currency-conversion-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
