server:
  port: 8761
spring:
  application:
    name: netflix-eureka-naming-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
