server:
  port: 8500

zuul:
  routes:
    currency-converter:
      path: /currency-converter/**
      serviceId: currency-conversion-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
